export interface PlaceCategory {
  value: string;
  label: string;
}

export const PLACE_CATEGORIES: PlaceCategory[] = [
  { value: 'restaurant', label: 'Restaurant' },
  { value: 'cafe', label: 'Café' },
  { value: 'bakery', label: 'Boulangerie' },
  { value: 'bar', label: 'Bar' },
  { value: 'pizza_restaurant', label: 'Pizzeria' },
  { value: 'fast_food_restaurant', label: 'Restauration rapide' },
  { value: 'ice_cream_shop', label: 'Glacier' },
  { value: 'night_club', label: 'Boîte de nuit / Discothèque' },

  { value: 'hair_salon', label: 'Salon de coiffure' },
  { value: 'beauty_salon', label: 'Institut de beauté' },
  { value: 'nail_salon', label: 'Salon de manucure' },
  { value: 'spa', label: 'Spa' },
  { value: 'massage', label: 'Massage / Bien-être' },
  { value: 'gym', label: 'Salle de sport' },
  { value: 'yoga_studio', label: 'Studio de yoga' },
  { value: 'tattoo_parlor', label: 'Salon de tatouage' },

  { value: 'clothing_store', label: 'Magasin de vêtements' },
  { value: 'shoe_store', label: 'Magasin de chaussures' },
  { value: 'jewelry_store', label: 'Bijouterie' },
  { value: 'florist', label: 'Fleuriste' },
  { value: 'pet_store', label: 'Animalerie' },
  { value: 'bicycle_store', label: 'Magasin de vélos' },
  { value: 'electronics_store', label: "Magasin d'électronique" },
  { value: 'home_goods_store', label: 'Magasin d\'articles pour la maison' },
  { value: 'furniture_store', label: 'Magasin de meubles' },
  { value: 'hardware_store', label: 'Quincaillerie' },
  { value: 'book_store', label: 'Librairie' },
  { value: 'supermarket', label: 'Supermarché' },
  { value: 'convenience_store', label: 'Supérette' },
  { value: 'liquor_store', label: 'Caviste' },
  { value: 'gift_shop', label: 'Boutique de cadeaux' },
  { value: 'toy_store', label: 'Magasin de jouets' },
  { value: 'sporting_goods_store', label: 'Magasin de sport' },

  { value: 'plumber', label: 'Plombier' },
  { value: 'electrician', label: 'Électricien' },
  { value: 'painter', label: 'Peintre en bâtiment' },
  { value: 'roofing_contractor', label: 'Couvreur' },
  { value: 'general_contractor', label: 'Entreprise du bâtiment' },
  { value: 'locksmith', label: 'Serrurier' },
  { value: 'moving_company', label: 'Déménageur' },
  { value: 'laundry', label: 'Pressing / Laverie' },
  { value: 'car_repair', label: 'Garage automobile' },
  { value: 'car_wash', label: 'Lavage auto' },
  { value: 'car_dealer', label: 'Concessionnaire automobile' },

  { value: 'dentist', label: 'Dentiste' },
  { value: 'doctor', label: 'Médecin' },
  { value: 'veterinary_care', label: 'Vétérinaire' },
  { value: 'physiotherapist', label: 'Kinésithérapeute' },
  { value: 'pharmacy', label: 'Pharmacie' },
  { value: 'optician', label: 'Opticien' },

  { value: 'lawyer', label: 'Avocat' },
  { value: 'real_estate_agency', label: 'Agence immobilière' },
  { value: 'insurance_agency', label: 'Assurance' },
  { value: 'accounting', label: 'Comptable' },
  { value: 'bank', label: 'Banque' },

  { value: 'tourist_attraction', label: 'Attraction touristique' },
  { value: 'museum', label: 'Musée' },
  { value: 'art_gallery', label: "Galerie d'art" },
  { value: 'movie_theater', label: 'Cinéma' },
  { value: 'bowling_alley', label: 'Bowling' },
  { value: 'amusement_park', label: "Parc d'attractions" },
  { value: 'park', label: 'Parc' },
];
